### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by mintsflandre** [alanzhangzm/Photon#11]
win7 64位，关闭软件时“Photon提示已停止工作”

**Comment by aixiu** [comment]
我也遇到了，开始以为是电脑问题，重新卸载又安装，换电脑，都是这样，同样是WIN7 64位

**Comment by alanzhangzm** [comment]
谢谢反馈，已在最新的0.3.1版本修复该bug

**Comment by aixiu** [comment]
@alanzhangzm 谢谢，终于修复了！~！用上了。
