### ISSUE TITLE
Win安装程序有错别字

### ISSUE THREAD

**Issue by ldsink** [alanzhangzm/Photon#13]
应该是“请稍候”，现在显示的是“稍后”。
稍候（wait a moment）
稍后（later/soon）
一个是稍微等一下的意思。一个是等下再来做的意思，还是有区别的。

**Comment by alanzhangzm** [comment]
安装程序是用第三方开源工具 electron-builder 打包的，你可以去项目主页 https://github.com/electron-userland/electron-builder 提这个问题。
