### ISSUE TITLE
Mac百度网盘无法下载

### ISSUE THREAD

**Issue by kiongweidong** [alanzhangzm/Photon#14]
插件是刚从GitHub下载的，但是下载的时候提示没有开启Aria2服务，请问这是什么情况，是我哪里安装不正确吗？

**Comment by Nenznay** [comment]
GitHub上下载的插件貌似会被Chrome浏览器禁用，你可以直接在Chrome应用商店下载，记得要搜索的是英文名称

**Comment by kiongweidong** [comment]
好的，知道了，问题已解决
