### ISSUE TITLE
NSIS Error

### ISSUE THREAD

**Issue by forward0401** [alanzhangzm/Photon#2]
![image](https://user-images.githubusercontent.com/31757662/40951941-d82d2a0e-68ab-11e8-95cf-2e2999ff62a6.png)
无法安装，win10家庭版，出现NSIS Error

**Comment by alanzhangzm** [comment]
@forward0401 从错误来看，似乎是因为你下载的安装文件损坏。请尝试重新下载后再次安装。如果你使用的是长城宽带之类的有cache问题的运营商，请尝试在主流运营商的网络下载。
