### ISSUE TITLE
Some files cannot be download, eg wechat.exe

### ISSUE THREAD

**Issue by ggplot-2** [alanzhangzm/Photon#4]

**Comment by mickeylzj** [comment]
Please provide specific link.
The following link can be downloaded successfully:
http://dldir1.qq.com/weixin/Windows/WeChat_C1012.exe

**Comment by python-lover** [comment]
The same link cannot be downloaded and the process bar always shows zero.
![image](https://user-images.githubusercontent.com/16712945/41076096-696aae96-6a42-11e8-9b7f-5f7ccb090be1.png)

win10 1709, 64 bit

**Comment by alanzhangzm** [comment]
I'm closing the issue because little detail is provided
