### ISSUE TITLE
关于 UI 设计的建议

### ISSUE THREAD

**Issue by 9E307** [alanzhangzm/Photon#8]
最近在用迅雷U享版，发现photon的界面和U享版布局差不多，但是还是欠缺 一些精致感，不知道开发者后续可以考虑按照U享版那样优化一下界面吗？

**Comment by alanzhangzm** [comment]
@9E307 很多年没有用过迅雷了，不过还是特意去看了你说的迅雷U享版，确实界面还是挺简洁精致的。我个人觉得，虽然 Photon 的界面可能像你说的那样没有那么精致，但是也还是简洁直观的。从功能的角度讲，现在的 UI 也不会给用户制造不方便的障碍。作为一个独立开发者，我的精力有限，我还是想把重心放在增加和优化软件的功能上。如果将来有大版本更新，那到时肯定会更新 UI，我会参考你推荐的迅雷 U 享版。
